# Generated by Django 3.2 on 2021-05-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fandamental',
            fields=[
                ('id', models.IntegerField()),
                ('meigara', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uriagetuuki1', models.FloatField(blank=True, null=True)),
                ('uriagetuuki2', models.FloatField(blank=True, null=True)),
                ('riekituuki1', models.FloatField(blank=True, null=True)),
                ('riekituuki2', models.FloatField(blank=True, null=True)),
                ('epstuuki1', models.FloatField(blank=True, null=True)),
                ('epstuuki2', models.FloatField(blank=True, null=True)),
                ('uriageshihanki1', models.FloatField(blank=True, null=True)),
                ('uriageshihanki2', models.FloatField(blank=True, null=True)),
                ('uriageshihanki3', models.FloatField(blank=True, null=True)),
                ('riekishihanki1', models.FloatField(blank=True, null=True)),
                ('riekishihanki2', models.FloatField(blank=True, null=True)),
                ('riekishihanki3', models.FloatField(blank=True, null=True)),
                ('epsshihanki1', models.FloatField(blank=True, null=True)),
                ('epsshihanki2', models.FloatField(blank=True, null=True)),
                ('epsshihanki3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realsimulation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('currency', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=255)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('days50', models.FloatField(blank=True, null=True)),
                ('days150', models.FloatField(blank=True, null=True)),
                ('days200', models.FloatField(blank=True, null=True)),
                ('weeks20', models.FloatField(blank=True, null=True)),
                ('stdev', models.FloatField(blank=True, null=True)),
                ('bb', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
