from django.db import models

# Create your models here.
class  Realsimulation(models.Model):
      id = models.IntegerField(primary_key=True) 
      date = models.DateTimeField()
      open = models.FloatField(null=True,blank=True)
      high = models.FloatField(null=True,blank=True)
      low = models.FloatField(null=True,blank=True)
      close = models.FloatField(null=True,blank=True)
      volume = models.IntegerField(null=True,blank=True)
      currency = models.CharField(max_length=255)
      code = models.CharField(max_length=255)
      rsi = models.FloatField(null=True,blank=True)
      days50 = models.FloatField(null=True,blank=True)
      days150 = models.FloatField(null=True,blank=True)
      days200 = models.FloatField(null=True,blank=True)
      weeks20 = models.FloatField(null=True,blank=True)
      stdev = models.FloatField(null=True,blank=True)
      bb = models.FloatField(null=True,blank=True)
      buy = models.CharField(max_length=255)
      sell = models.CharField(max_length=255)
      version = models.CharField(max_length=255)
      def __str__(self):
            return self.code

class Fandamental(models.Model):
      id = models.IntegerField() 
      meigara = models.CharField(max_length=255)
      code = models.CharField(max_length=255,primary_key=True)
      uriagetuuki1 = models.FloatField(null=True,blank=True)
      uriagetuuki2 = models.FloatField(null=True,blank=True)
      riekituuki1 = models.FloatField(null=True,blank=True)
      riekituuki2 = models.FloatField(null=True,blank=True)
      epstuuki1 = models.FloatField(null=True,blank=True)
      epstuuki2 = models.FloatField(null=True,blank=True)
      uriageshihanki1 =models.FloatField(null=True,blank=True)
      uriageshihanki2 =models.FloatField(null=True,blank=True)
      uriageshihanki3 =models.FloatField(null=True,blank=True)
      riekishihanki1 =models.FloatField(null=True,blank=True)
      riekishihanki2 =models.FloatField(null=True,blank=True)
      riekishihanki3 =models.FloatField(null=True,blank=True)
      epsshihanki1 =models.FloatField(null=True,blank=True)
      epsshihanki2 =models.FloatField(null=True,blank=True)
      epsshihanki3 =models.FloatField(null=True,blank=True)

class  Realsimulation_v1(models.Model):
      id = models.IntegerField(primary_key=True) 
      Date = models.DateTimeField()
      Open = models.FloatField(null=True,blank=True)
      High = models.FloatField(null=True,blank=True)
      Low = models.FloatField(null=True,blank=True)
      Close = models.FloatField(null=True,blank=True)
      Volume = models.IntegerField(null=True,blank=True)
      Currency = models.CharField(max_length=255)
      code = models.CharField(max_length=255)
      rsi = models.FloatField(null=True,blank=True)
      days50 = models.FloatField(null=True,blank=True)
      days150 = models.FloatField(null=True,blank=True)
      days200 = models.FloatField(null=True,blank=True)
      weeks20 = models.FloatField(null=True,blank=True)
      stdev = models.FloatField(null=True,blank=True)
      BB = models.FloatField(null=True,blank=True)
      buy = models.CharField(max_length=255)
      sell = models.CharField(max_length=255)
      version = models.CharField(max_length=255)

class Fanda(models.Model):
      id = models.IntegerField(primary_key=True) 
      code = models.CharField(max_length=255)
      kessan_0 = models.DateTimeField()
      uriage_0 = models.CharField(max_length=255)
      rieki_0 = models.CharField(max_length=255)
      kessan_1 = models.DateTimeField()
      uriage_1 = models.CharField(max_length=255)
      rieki_1 = models.CharField(max_length=255)
      kessan_2 = models.DateTimeField()
      uriage_2 = models.CharField(max_length=255)
      rieki_2 = models.CharField(max_length=255)
      kessan_3= models.DateTimeField()
      uriage_3 = models.CharField(max_length=255)
      rieki_3 = models.CharField(max_length=255)
      kessan_4 = models.DateTimeField()
      uriage_4 = models.CharField(max_length=255)
      rieki_4 = models.CharField(max_length=255)
      kessan_5 = models.DateTimeField()
      uriage_5 = models.CharField(max_length=255)
      rieki_5 = models.CharField(max_length=255)
      kessan_6 = models.DateTimeField()
      uriage_6 = models.CharField(max_length=255)
      rieki_6 = models.CharField(max_length=255)
      kessan_7 = models.DateTimeField()
      uriage_7 = models.CharField(max_length=255)
      rieki_7 = models.CharField(max_length=255)
      uriage_jousyou_0 = models.IntegerField(null=True,blank=True)
      rieki_jousyou_0 = models.IntegerField(null=True,blank=True)
      uriage_jousyou_1 = models.IntegerField(null=True,blank=True)
      rieki_jousyou_1 = models.IntegerField(null=True,blank=True)
      uriage_jousyou_2 = models.IntegerField(null=True,blank=True)
      rieki_jousyou_2 = models.IntegerField(null=True,blank=True)
      uriage_jousyou_3 = models.IntegerField(null=True,blank=True)
      rieki_jousyou_3 = models.IntegerField(null=True,blank=True)