from django.db import models
from django.urls import reverse_lazy

class  Realsimulation_v1(models.Model):
      id = models.IntegerField(primary_key=True) 
      Date = models.DateTimeField()
      Open = models.FloatField(null=True,blank=True)
      High = models.FloatField(null=True,blank=True)
      Low = models.FloatField(null=True,blank=True)
      Close = models.FloatField(null=True,blank=True)
      Volume = models.IntegerField(null=True,blank=True)
      Currency = models.CharField(max_length=255)
      code = models.CharField(max_length=255)
      rsi = models.FloatField(null=True,blank=True)
      days50 = models.FloatField(null=True,blank=True)
      days150 = models.FloatField(null=True,blank=True)
      days200 = models.FloatField(null=True,blank=True)
      weeks20 = models.FloatField(null=True,blank=True)
      stdev = models.FloatField(null=True,blank=True)
      BB = models.FloatField(null=True,blank=True)
      buy = models.CharField(max_length=255)
      sell = models.CharField(max_length=255)
      version = models.CharField(max_length=255)

class Fanda(models.Model):
      id = models.IntegerField(primary_key=True) 
      code = models.CharField(max_length=255)
      name = models.CharField(max_length=255)
      y_k_0 = models.CharField(max_length=255)
      y_u_0 = models.IntegerField(null=True,blank=True)
      y_er_0 = models.IntegerField(null=True,blank=True)
      y_kr_0 = models.IntegerField(null=True,blank=True)
      y_e_0 = models.IntegerField(null=True,blank=True)
      y_k_1 = models.CharField(max_length=255)
      y_u_1 = models.IntegerField(null=True,blank=True)
      y_er_1 = models.IntegerField(null=True,blank=True)
      y_kr_1 = models.IntegerField(null=True,blank=True)
      y_e_1 = models.IntegerField(null=True,blank=True)
      y_k_2 = models.CharField(max_length=255)
      y_u_2 = models.IntegerField(null=True,blank=True)
      y_er_2 = models.IntegerField(null=True,blank=True)
      y_kr_2 = models.IntegerField(null=True,blank=True)
      y_e_2 = models.IntegerField(null=True,blank=True)
      y_k_3 = models.CharField(max_length=255)
      y_u_3 = models.IntegerField(null=True,blank=True)
      y_er_3 = models.IntegerField(null=True,blank=True)
      y_kr_3 = models.IntegerField(null=True,blank=True)
      y_e_3 = models.IntegerField(null=True,blank=True)
      y_k_4 = models.CharField(max_length=255)
      y_u_4 = models.IntegerField(null=True,blank=True)
      y_er_4 = models.IntegerField(null=True,blank=True)
      y_kr_4 = models.IntegerField(null=True,blank=True)
      y_e_4 = models.IntegerField(null=True,blank=True)
      y_k_5 = models.CharField(max_length=255)
      y_u_5 = models.IntegerField(null=True,blank=True)
      y_er_5 = models.IntegerField(null=True,blank=True)
      y_kr_5 = models.IntegerField(null=True,blank=True)
      y_e_5 = models.IntegerField(null=True,blank=True)
      y_k_6 = models.CharField(max_length=255)
      y_u_6 = models.IntegerField(null=True,blank=True)
      y_er_6 = models.IntegerField(null=True,blank=True)
      y_kr_6 = models.IntegerField(null=True,blank=True)
      y_e_6 = models.IntegerField(null=True,blank=True)
      y_k_7 = models.CharField(max_length=255)
      y_u_7 = models.IntegerField(null=True,blank=True)
      y_er_7 = models.IntegerField(null=True,blank=True)
      y_kr_7 = models.IntegerField(null=True,blank=True)
      y_e_7 = models.IntegerField(null=True,blank=True)
      y_k_8 = models.CharField(max_length=255)
      y_u_8 = models.IntegerField(null=True,blank=True)
      y_er_8 = models.IntegerField(null=True,blank=True)
      y_kr_8 = models.IntegerField(null=True,blank=True)
      y_e_8 = models.IntegerField(null=True,blank=True)
      y_k_9 = models.CharField(max_length=255)
      y_u_9 = models.IntegerField(null=True,blank=True)
      y_er_9 = models.IntegerField(null=True,blank=True)
      y_kr_9 = models.IntegerField(null=True,blank=True)
      y_e_9 = models.IntegerField(null=True,blank=True)
      y_k_10 = models.CharField(max_length=255)
      y_u_10 = models.IntegerField(null=True,blank=True)
      y_er_10 = models.IntegerField(null=True,blank=True)
      y_kr_10 = models.IntegerField(null=True,blank=True)
      y_e_10 = models.IntegerField(null=True,blank=True)
      y_k_11 = models.CharField(max_length=255)
      y_u_11 = models.IntegerField(null=True,blank=True)
      y_er_11 = models.IntegerField(null=True,blank=True)
      y_kr_11 = models.IntegerField(null=True,blank=True)
      y_e_11 = models.IntegerField(null=True,blank=True)
      s_k_0 = models.CharField(max_length=255)
      s_u_0 = models.IntegerField(null=True,blank=True)
      s_er_0 = models.IntegerField(null=True,blank=True)
      s_kr_0 = models.IntegerField(null=True,blank=True)
      s_e_0 = models.IntegerField(null=True,blank=True)
      s_k_1 = models.CharField(max_length=255)
      s_u_1 = models.IntegerField(null=True,blank=True)
      s_er_1 = models.IntegerField(null=True,blank=True)
      s_kr_1 = models.IntegerField(null=True,blank=True)
      s_e_1 = models.IntegerField(null=True,blank=True)
      s_k_2 = models.CharField(max_length=255)
      s_u_2 = models.IntegerField(null=True,blank=True)
      s_er_2 = models.IntegerField(null=True,blank=True)
      s_kr_2 = models.IntegerField(null=True,blank=True)
      s_e_2 = models.IntegerField(null=True,blank=True)
      s_k_3 = models.CharField(max_length=255)
      s_u_3 = models.IntegerField(null=True,blank=True)
      s_er_3 = models.IntegerField(null=True,blank=True)
      s_kr_3 = models.IntegerField(null=True,blank=True)
      s_e_3 = models.IntegerField(null=True,blank=True)
      s_k_4 = models.CharField(max_length=255)
      s_u_4 = models.IntegerField(null=True,blank=True)
      s_er_4 = models.IntegerField(null=True,blank=True)
      s_kr_4 = models.IntegerField(null=True,blank=True)
      s_e_4 = models.IntegerField(null=True,blank=True)
      s_k_5 = models.CharField(max_length=255)
      s_u_5 = models.IntegerField(null=True,blank=True)
      s_er_5 = models.IntegerField(null=True,blank=True)
      s_kr_5 = models.IntegerField(null=True,blank=True)
      s_e_5 = models.IntegerField(null=True,blank=True)
      s_k_6 = models.CharField(max_length=255)
      s_u_6 = models.IntegerField(null=True,blank=True)
      s_er_6 = models.IntegerField(null=True,blank=True)
      s_kr_6 = models.IntegerField(null=True,blank=True)
      s_e_6 = models.IntegerField(null=True,blank=True)
      s_k_7 = models.CharField(max_length=255)
      s_u_7 = models.IntegerField(null=True,blank=True)
      s_er_7 = models.IntegerField(null=True,blank=True)
      s_kr_7 = models.IntegerField(null=True,blank=True)
      s_e_7 = models.IntegerField(null=True,blank=True)
      s_k_8 = models.CharField(max_length=255)
      s_u_8 = models.IntegerField(null=True,blank=True)
      s_er_8 = models.IntegerField(null=True,blank=True)
      s_kr_8 = models.IntegerField(null=True,blank=True)
      s_e_8 = models.IntegerField(null=True,blank=True)
      s_k_9 = models.CharField(max_length=255)
      s_u_9 = models.IntegerField(null=True,blank=True)
      s_er_9 = models.IntegerField(null=True,blank=True)
      s_kr_9 = models.IntegerField(null=True,blank=True)
      s_e_9 = models.IntegerField(null=True,blank=True)
      s_k_10 = models.CharField(max_length=255)
      s_u_10 = models.IntegerField(null=True,blank=True)
      s_er_10 = models.IntegerField(null=True,blank=True)
      s_kr_10 = models.IntegerField(null=True,blank=True)
      s_e_10 = models.IntegerField(null=True,blank=True)
      s_k_11 = models.CharField(max_length=255)
      s_u_11 = models.IntegerField(null=True,blank=True)
      s_er_11 = models.IntegerField(null=True,blank=True)
      s_kr_11 = models.IntegerField(null=True,blank=True)
      s_e_11 = models.IntegerField(null=True,blank=True)
      s_k_12 = models.CharField(max_length=255)
      s_u_12 = models.IntegerField(null=True,blank=True)
      s_er_12 = models.IntegerField(null=True,blank=True)
      s_kr_12 = models.IntegerField(null=True,blank=True)
      s_e_12 = models.IntegerField(null=True,blank=True)
      s_k_13 = models.CharField(max_length=255)
      s_u_13 = models.IntegerField(null=True,blank=True)
      s_er_13 = models.IntegerField(null=True,blank=True)
      s_kr_13 = models.IntegerField(null=True,blank=True)
      s_e_13 = models.IntegerField(null=True,blank=True)
      s_k_14 = models.CharField(max_length=255)
      s_u_14 = models.IntegerField(null=True,blank=True)
      s_er_14 = models.IntegerField(null=True,blank=True)
      s_kr_14 = models.IntegerField(null=True,blank=True)
      s_e_14 = models.IntegerField(null=True,blank=True)
      s_k_15 = models.CharField(max_length=255)
      s_u_15 = models.IntegerField(null=True,blank=True)
      s_er_15 = models.IntegerField(null=True,blank=True)
      s_kr_15 = models.IntegerField(null=True,blank=True)
      s_e_15 = models.IntegerField(null=True,blank=True)
      s_k_16 = models.CharField(max_length=255)
      s_u_16 = models.IntegerField(null=True,blank=True)
      s_er_16 = models.IntegerField(null=True,blank=True)
      s_kr_16 = models.IntegerField(null=True,blank=True)
      s_e_16 = models.IntegerField(null=True,blank=True)
      s_k_17 = models.CharField(max_length=255)
      s_u_17 = models.IntegerField(null=True,blank=True)
      s_er_17 = models.IntegerField(null=True,blank=True)
      s_kr_17 = models.IntegerField(null=True,blank=True)
      s_e_17 = models.IntegerField(null=True,blank=True)
      s_k_18 = models.CharField(max_length=255)
      s_u_18 = models.IntegerField(null=True,blank=True)
      s_er_18 = models.IntegerField(null=True,blank=True)
      s_kr_18 = models.IntegerField(null=True,blank=True)
      s_e_18 = models.IntegerField(null=True,blank=True)
      s_k_19 = models.CharField(max_length=255)
      s_u_19 = models.IntegerField(null=True,blank=True)
      s_er_19 = models.IntegerField(null=True,blank=True)
      s_kr_19 = models.IntegerField(null=True,blank=True)
      s_e_19 = models.IntegerField(null=True,blank=True)
      def __str__(self) :
          return self.code

class Realsimulation_result_v1(models.Model):
      Code = models.CharField(max_length=255)
      Buy_date = models.DateTimeField()
      Buy_cost = models.FloatField(null=True,blank=True)
      Day50_day200 = models.FloatField(null=True,blank=True)
      Sell_date = models.DateTimeField()
      Sell_cost = models.FloatField(null=True,blank=True)
      Profit_and_lost =models.FloatField(null=True,blank=True)
      Sell_pattern = models.CharField(max_length=255)
      Version = models.CharField(max_length=255)
      No = models.IntegerField(null=True,blank=True)
      Id = models.IntegerField(primary_key=True)
      def __str__(self) :
          return str(self.Code)

class Category(models.Model):
      name = models.CharField(max_length=255,blank=False,null=False,unique=True)
      def __str__(self):
            return self.name

class Tag(models.Model):
      name = models.CharField(max_length=255,blank=False,null=False,unique=True)
      def __str__(self):
            return self.name

class Post(models.Model):
      created = models.DateTimeField(auto_now_add=True,editable=False,blank=False,null=False)
      updated = models.DateTimeField(auto_now=True,editable=False,blank=False,null=False)
      title = models.CharField(max_length=255,blank=False,null=False)
      body = models.TextField(blank=True,null=False)
      category = models.ForeignKey(Category,on_delete=models.CASCADE)
      tags = models.ManyToManyField(Tag,blank=True)
      def __str__(self):
        return self.title
      def get_absolute_url(self):
            # reverse_lazy(urlconf,args=[id])はテンプレートでいう{% url "urlconf" id%}
            return reverse_lazy("test_app:detail",args=[self.id])